module.exports = [
  "strapi::errors",
  "strapi::security",
  "strapi::cors",
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
  "global::users-find",
  "global::users-create",
  "global::register",
  "global::intercept-from-gtb",
  "global::intercept-from-fgtb",
];
